---
- name: Manage Realm
  community.general.keycloak_realm:
    # Auth Params
    auth_username: "{{ auth_username }}"
    auth_password: "{{ auth_password }}"
    auth_realm: "{{ auth_realm | default('master') }}"
    auth_keycloak_url: "{{ auth_keycloak_url }}"
    validate_certs: "{{ validate_certs }}"

    # Realm Base Params
    display_name: "{{ display_name }}"
    display_name_html: "{{ display_name_html }}"
    id: "{{ id }}"
    realm: "{{ realm }}"

    #access_code_lifespan: "{{ access_code_lifespan }}"
    #access_code_lifespan_login: "{{ access_code_lifespan_login }}"
    #access_code_lifespan_user_action: "{{ access_code_lifespan_user_action }}"
    #access_token_lifespan: "{{ access_token_lifespan }}"
    #access_token_lifespan_for_implicit_flow: "{{ access_token_lifespan_for_implicit_flow }}"
    #account_theme: "{{ account_theme }}"
    #action_token_generated_by_admin_lifespan: "{{ action_token_generated_by_admin_lifespan }}"
    #action_token_generated_by_user_lifespan: "{{ action_token_generated_by_user_lifespan }}"
    #admin_events_details_enabled: "{{ admin_events_details_enabled }}"
    #admin_events_enabled: "{{ admin_events_enabled }}"
    #admin_theme: "{{ admin_theme }}"
    #attributes: "{{ attributes }}"
    #browser_flow: "{{ browser_flow }}"
    #browser_security_headers: "{{ browser_security_headers }}"
    #brute_force_protected: "{{ brute_force_protected }}"
    #client_authentication_flow: "{{ client_authentication_flow }}"
    #client_scope_mappings: "{{ client_scope_mappings }}"
    #connection_timeout: "{{ connection_timeout }}"
    #default_default_client_scopes: "{{ default_default_client_scopes }}"
    #default_groups: "{{ default_groups }}"
    #default_locale: "{{ default_locale }}"
    #default_optional_client_scopes: "{{ default_optional_client_scopes }}"
    #default_roles: "{{ default_roles }}"
    #default_signature_algorithm: "{{ default_signature_algorithm }}"
    #direct_grant_flow: "{{ direct_grant_flow }}"
    #docker_authentication_flow: "{{ docker_authentication_flow }}"
    #duplicate_emails_allowed: "{{ duplicate_emails_allowed }}"
    #edit_username_allowed: "{{ edit_username_allowed }}"
    #email_theme: "{{ email_theme }}"
    #enabled: "{{ enabled }}"
    #enabled_event_types: "{{ enabled_event_types }}"
    #events_enabled: "{{ events_enabled }}"
    #events_expiration: "{{ events_expiration }}"
    #events_listeners: "{{ events_listeners }}"
    #failure_factor: "{{ failure_factor }}"
    #http_agent: "{{ http_agent }}"
    #internationalization_enabled: "{{ internationalization_enabled }}"
    #login_theme: "{{ login_theme }}"
    #login_with_email_allowed: "{{ login_with_email_allowed }}"
    #max_delta_time_seconds: "{{ max_delta_time_seconds }}"
    #max_failure_wait_seconds: "{{ max_failure_wait_seconds }}"
    #minimum_quick_login_wait_seconds: "{{ minimum_quick_login_wait_seconds }}"
    #not_before: "{{ not_before }}"
    #offline_session_idle_timeout: "{{ offline_session_idle_timeout }}"
    #offline_session_max_lifespan: "{{ offline_session_max_lifespan }}"
    #offline_session_max_lifespan_enabled: "{{ offline_session_max_lifespan_enabled }}"
    #otp_policy_algorithm: "{{ otp_policy_algorithm }}"
    #otp_policy_digits: "{{ otp_policy_digits }}"
    #otp_policy_initial_counter: "{{ otp_policy_initial_counter }}"
    #otp_policy_look_ahead_window: "{{ otp_policy_look_ahead_window }}"
    #otp_policy_period: "{{ otp_policy_period }}"
    #otp_policy_type: "{{ otp_policy_type }}"
    #otp_supported_applications: "{{ otp_supported_applications }}"
    #password_policy: "{{ password_policy }}"
    #permanent_lockout: "{{ permanent_lockout }}"
    #quick_login_check_milli_seconds: "{{ quick_login_check_milli_seconds }}"
    #refresh_token_max_reuse: "{{ refresh_token_max_reuse }}"
    #registration_allowed: "{{ registration_allowed }}"
    #registration_email_as_username: "{{ registration_email_as_username }}"
    #registration_flow: "{{ registration_flow }}"
    #remember_me: "{{ remember_me }}"
    #reset_credentials_flow: "{{ reset_credentials_flow }}"
    #reset_password_allowed: "{{ reset_password_allowed }}"
    #revoke_refresh_token: "{{ revoke_refresh_token }}"
    #smtp_server: "{{ smtp_server }}"
    #ssl_required: "{{ ssl_required }}"
    #sso_session_idle_timeout: "{{ sso_session_idle_timeout }}"
    #sso_session_idle_timeout_remember_me: "{{ sso_session_idle_timeout_remember_me }}"
    #sso_session_max_lifespan: "{{ sso_session_max_lifespan }}"
    #sso_session_max_lifespan_remember_me: "{{ sso_session_max_lifespan_remember_me }}"
    #state: "{{ state }}"
    #supported_locales: "{{ supported_locales }}"
    #user_managed_access_allowed: "{{ user_managed_access_allowed }}"
    #validate_certs: "{{ validate_certs }}"
    #verify_email: "{{ verify_email }}"
    #wait_increment_seconds: "{{ wait_increment_seconds }}"
